---
language: python
python: "3.5"

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - python3-pip
    - lxc
    - python3-lxc
  hosts:
    - lxc-webpanel

script:
  - python3 install/setup.py
