---
language: python
python: "3.5"

sudo: required
dist: trusty

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - python-dev
    - build-essential
    - lxc
    - lxc-dev
  hosts:
    - lxc-webpanel

script:
  - pip install git+https://github.com/lxc/lxc.git#subdirectory=src/python-lxc
  - python3 install/setup.py
