---
language: python
python: "3.5"

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-lxc/stable
  - sudo apt-get update
  - sudo apt-get install lxc lxc-dev python3-lxc

addons:
  apt:
    packages:
    - python-dev
    - build-essential

script:
  - pip install git+https://github.com/lxc/lxc.git#subdirectory=src/python-lxc
  - python3 install/setup.py
