---
language: python
python: "3.5_with_system_site_packages"

sudo: required
dist: trusty

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - python-dev
    - build-essential
    - lxc
    - lxc-dev

script:
  - pip install git+https://github.com/lxc/lxc.git#subdirectory=src/python-lxc
  - python3 install/setup.py
