---
language: python
python: "3.5"

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - python3-pip
    - lxc
    - lxc-dev
  hosts:
    - lxc-webpanel

script:
  - pip install git+https://github.com/lxc/lxc.git#subdirectory=src/python-lxc
  - python3 install/setup.py
