---
language: python
python: "3.5"

sudo: required
dist: trusty

script:
  - sudo apt-get install python3-pip
  - sudo apt-get install lxc
  - sudo apt-get install python-lxc
  - git submodule update --init
  - pip install -r requirements.txt
  - python3 install/setup.py
